### ISSUE TITLE
Failed to save model when running built-in training commands

### ISSUE THREAD

**Issue by wangz10** [awslabs/graphstorm#175]
Hello team,

I got the an error when running the Arxiv node classification using the built-in commands inside the docker container: 

```
python3  -m graphstorm.run.gs_node_classification \
        --workspace /tmp/ogbn-arxiv-nc \
        --num-trainers 1 \
        --num-servers 1 \
        --num-samplers 0 \
        --part-config /tmp/ogbn_arxiv_nc_1p/ogbn-arxiv.json \
        --ip-config  /tmp/ogbn-arxiv-nc/ip_list.txt \
        --ssh-port 2222 \
        --cf /graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml \
        --save-model-path /tmp/ogbn-arxiv-nc/models
```

Here is the error message: 

```
Step 890 | Validation accuracy: 0.6565
Step 890 | Test accuracy: 0.6320
Step 890 | Best Validation accuracy: 0.6622
Step 890 | Best Test accuracy: 0.6424
Step 890 | Best Iteration accuracy: 712.0000
 Eval time: 5.3871, Evaluation step: 890.0000
Peak Mem alloc: 355.8843 MB
best_test_score: {'accuracy': 0.6423883299384812}
best_val_score: {'accuracy': 0.6622369878183831}
peak_mem_alloc_MB: 355.88427734375
Traceback (most recent call last):
  File "/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 134, in <module>
    main(args)
  File "/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 102, in main
    trainer.fit(train_loader=dataloader, val_loader=val_dataloader,
  File "/graphstorm/python/graphstorm/trainer/np_trainer.py", line 212, in fit
    self.save_model_results_to_file(self.evaluator.best_test_score,
  File "/graphstorm/python/graphstorm/trainer/gsgnn_trainer.py", line 292, in save_model_results_to_file
    save_model_results_json(conf=conf,
  File "/graphstorm/python/graphstorm/model/utils.py", line 98, in save_model_results_json
    with open(json_path, 'w', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ogbn-arxiv-nc/models/performance_results.json'
Client[0] in group[0] is exiting...
Namespace(ip_config='/tmp/ogbn-arxiv-nc/ip_list.txt', local_rank=-1, part_config='/tmp/ogbn_arxiv_nc_1p/ogbn-arxiv.json', save_perf_results_path='/tmp/ogbn-arxiv-nc/models', verbose=False, yaml_config_file='/graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml')
{'version': 1.0, 'gsf': {'basic': {'model_encoder_type': 'rgcn', 'graph_name': 'ogbn-arxiv', 'backend': 'gloo', 'ip_config': 'ip_list.txt', 'part_config': '/data/ogbn-arxiv-1p/ogbn-arxiv.json', 'verbose': False}, 'gnn': {'fanout': '15,10', 'num_layers': 2, 'hidden_size': 128, 'use_mini_batch_infer': False}, 'input': {'restore_model_path': None}, 'output': {'save_model_path': None, 'save_embed_path': None}, 'hyperparam': {'dropout': 0.5, 'lr': 0.001, 'num_epochs': 10, 'batch_size': 1024, 'wd_l2norm': 0}, 'rgcn': {'num_bases': -1, 'use_self_loop': True, 'sparse_optimizer_lr': '1e-2', 'use_node_embeddings': False}, 'node_classification': {'target_ntype': 'node', 'label_field': 'labels', 'multilabel': False, 'num_classes': 40}}}
Overriding Argument: save_perf_results_path
Overriding Argument: ip_config
Overriding Argument: part_config
Overriding Argument: verbose
load ogbn-arxiv
start graph service on server 0 for part 0
Server is waiting for connections on [127.0.0.1:30050]...
Server (0) shutdown.
Server is exiting...
/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 358) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-15_14:30:57
  host      : ip-172-16-48-72.us-west-2.compute.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 358)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Called process error Command 'ssh -o StrictHostKeyChecking=no -p 2222 127.0.0.1 'cd /tmp/ogbn-arxiv-nc; (export DGL_DIST_MODE=distributed DGL_ROLE=client DGL_NUM_SAMPLER=0 DGL_NUM_CLIENT=1 DGL_CONF_PATH=/tmp/ogbn_arxiv_nc_1p/ogbn-arxiv.json DGL_IP_CONFIG=/tmp/ogbn-arxiv-nc/ip_list.txt DGL_NUM_SERVER=1 DGL_GRAPH_FORMAT=csc OMP_NUM_THREADS=8 DGL_GROUP_ID=0 PYTHONPATH=/graphstorm/python/: ; /usr/bin/python3 -m torch.distributed.launch --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=1234 /graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py --cf /graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml --save-perf-results-path /tmp/ogbn-arxiv-nc/models --ip-config /tmp/ogbn-arxiv-nc/ip_list.txt --part-config /tmp/ogbn_arxiv_nc_1p/ogbn-arxiv.json --verbose False)'' returned non-zero exit status 1.
Task failed
```

**Comment by zhjwy9343** [comment]
Yes, we are refactoring all arguments to make their format consistent. Please wait one or two days and pull the latest codes.

**Comment by zheng-da** [comment]
is this still a problem? @wangz10

**Comment by wangz10** [comment]
This is resolved
