### ISSUE TITLE
DGL graph construction got stuck in Amazon x1e instance type.

### ISSUE THREAD

**Issue by HouyuZhang1007** [awslabs/graphstorm#238]
I'm building docker image by following:
```
sudo mkdir /codes
sudo chmod -R 777 /codes
cd /codes
git clone https://github.com/awslabs/graphstorm
cd /codes/graphstorm/docker/
bash /codes/graphstorm/docker/build_docker_oss4local.sh /codes/graphstorm/ graphstorm local

# create container:
# if g5:
nvidia-docker run -t -d --name graph_storm --network=host -v /fsx-CoreModeling/zhanhouy/home/:/fsx-CoreModeling/zhanhouy/home --shm-size=374g graphstorm:local

# if x1e:
docker run -t -d --name graph_storm --network=host -v /fsx-CoreModeling/zhanhouy/home/:/fsx-CoreModeling/zhanhouy/home --shm-size=1800g graphstorm:local 

# log in container:
docker container exec -it graph_storm /bin/bash
```

Inside container, I tried to build DGL graph for a toy graph in g5 instance, which works well. However, when I tried to build the DGL graph for the same toy graph in x1e instance, it got stuck forever without any log. I then killed the job and the traceback shows like this:
```
Traceback (most recent call last):
 File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
  self.run()
 File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
  self._target(*self._args, **self._kwargs)
 File "/graphstorm/python/graphstorm/gconstruct/utils.py", line 180, in worker_fn
  res_queue.put((i, data))
 File "<string>", line 2, in put
 File "/usr/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
  kind, result = conn.recv()
 File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
  buf = self._recv_bytes()
 File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
  buf = self._recv(4)
 File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
  chunk = read(handle, remaining)
```
I tried 4 workers and 10 workers and both got stuck.

**Comment by zheng-da** [comment]
can you also provide the command of running graph construction pipeline?

**Comment by HouyuZhang1007** [comment]
graphstorm_graph_construct_config.json
```
{
    "nodes": [
        {
           "node_id_col":  "ids",
           "node_type":    "query",
           "format":       {"name": "parquet"},
           "files":        "/fsx-CoreModeling/zhanhouy/home/m5gnn_dataset/search_ranking/2clicks-001ctr-20maxa2a-debug-json-graph/nfeats-query/embeddings/*.parquet",
           "features":     [
               {
                   "feature_col":  "embeddings",
                   "feature_name": "embeddings"
               }
           ]
        },
        {
           "node_id_col":  "ids",
           "node_type":    "asin",
           "format":       {"name": "parquet"},
           "files":        "/fsx-CoreModeling/zhanhouy/home/m5gnn_dataset/search_ranking/2clicks-001ctr-20maxa2a-debug-json-graph/nfeats-asin/embeddings/*.parquet",
           "features":     [
               {
                   "feature_col":  "embeddings",
                   "feature_name": "embeddings"
               }
           ]
        }
    ],
    "edges": [
            {
                "source_id_col":    "src_id",
                "dest_id_col":      "dst_id",
                "relation":         ["query", "clicks", "asin"],
                "format":           {"name": "json"},
                "files":        "/fsx-CoreModeling/zhanhouy/home/m5gnn_dataset/search_ranking/2clicks-001ctr-20maxa2a-debug-json-graph/edges-query_clicks_asin/*.json",
               "features":     [
                   {
                        "feature_col":  "true_num_adds_sum"
                   },
                   {
                        "feature_col":  "true_num_clicks_sum"
                   },
                   {
                        "feature_col":  "true_num_consumes_sum"
                   },
                   {
                        "feature_col":  "true_num_purchases_sum"
                   },
                   {
                        "feature_col":  "num_impressions_sum"
                   },
                   {
                        "feature_col":  "ctr"
                   },
                   {    
                        "feature_col": "uber_bvhist_scaled"
                   },
                   {    
                        "feature_col": "uber_qn_bvhist_scaled"
                   },
                   {
                        "feature_col":  "train",
                        "feature_name": "train_mask"
                   },
                   {
                        "feature_col":  "valid",
                        "feature_name": "val_mask"
                   },
                   {
                        "feature_col":  "test",
                        "feature_name": "test_mask"
                   }
                ]
            },
            {
                "source_id_col":    "src_id",
                "dest_id_col":      "dst_id",
                "relation":         ["query", "target", "asin"],
                "format":           {"name": "json"},
                "files":        "/fsx-CoreModeling/zhanhouy/home/m5gnn_dataset/search_ranking/2clicks-001ctr-20maxa2a-debug-json-graph/edges-query_target_asin/*.json",
               "features":     [
                   {
                        "feature_col":  "true_num_adds_sum"
                   },
                   {
                        "feature_col":  "true_num_clicks_sum"
                   },
                   {
                        "feature_col":  "true_num_consumes_sum"
                   },
                   {
                        "feature_col":  "true_num_purchases_sum"
                   },
                   {
                        "feature_col":  "num_impressions_sum"
                   },
                   {
                        "feature_col":  "ctr"
                   },
                   {    
                        "feature_col": "uber_bvhist_scaled"
                   },
                   {    
                        "feature_col": "uber_qn_bvhist_scaled"
                   },
                   {
                        "feature_col":  "train",
                        "feature_name": "train_mask"
                   },
                   {
                        "feature_col":  "valid",
                        "feature_name": "val_mask"
                   },
                   {
                        "feature_col":  "test",
                        "feature_name": "test_mask"
                   }
                ]
            },
            {
                "source_id_col":    "src_id",
                "dest_id_col":      "dst_id",
                "relation":         ["asin", "substitutes", "asin"],
                "format":           {"name": "json"},
                "files":        "/fsx-CoreModeling/zhanhouy/home/m5gnn_dataset/search_ranking/2clicks-001ctr-20maxa2a-debug-json-graph/edges-asin_substitutes_asin/*.json"
            }
    ]
}
```

run.sh:
```
#! /bin/bash
GRAPH_NAME=2clicks-001ctr-20maxa2a-debug-embed-gs
CONFIG_FILE=/fsx-CoreModeling/zhanhouy/home/workspace/m5-gnn/m5-gnn/python/m5gnn/examples/search_ranking/graphstorm_graph_construct_config.json
NUM_DATASET_WORKERS=10
NUM_PART=1
OUTPUT=/fsx-CoreModeling/zhanhouy/home/m5gnn_dataset/search_ranking/${GRAPH_NAME}-dgl-graph
DIST_OUTPUT=${OUTPUT}/dist_${NUM_PART}
python3 -m graphstorm.gconstruct.construct_graph \
            --conf-file ${CONFIG_FILE} \
            --num-processes ${NUM_DATASET_WORKERS} \
            --num-parts ${NUM_PART} \
            --output-dir ${DIST_OUTPUT} \
            --graph-name ${GRAPH_NAME} \
            --add-reverse-edges
```
