### ISSUE TITLE
[Bug] Failing to load optimizer state of `lm`

### ISSUE THREAD

**Issue by wangz10** [awslabs/graphstorm#304]
I run into this error when trying to restore model and optimizer from checkpoint: 

```
Node node adds lm bert features 0->768
Node node has 768 features.
load GNN model from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
load GNN model from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
load GNN model from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
load GNN model from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
load GNN model from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
Load Sparse embedding from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
Load Sparse embedding from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
Load Sparse embedding from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
Load Sparse embedding from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
Load Sparse embedding from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
Load Sparse embedding from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
Load Sparse embedding from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
Load Sparse embedding from  /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0
Traceback (most recent call last):
  File "/develop/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 142, in <module>
    main(args)
  File "/develop/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 70, in main
    trainer.restore_model(model_path=config.restore_model_path)
  File "/develop/graphstorm/python/graphstorm/trainer/gsgnn_trainer.py", line 330, in restore_model
    self._optimizer.load_opt_state(model_path, self._model.device)
  File "/develop/graphstorm/python/graphstorm/model/gnn.py", line 100, in load_opt_state
    load_opt_state(path, self.dense_opts, self.lm_opts, self.sparse_opts)
  File "/develop/graphstorm/python/graphstorm/model/utils.py", line 609, in load_opt_state
    dense_opts[0].load_state_dict(checkpoint["lm"])
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/optimizer.py", line 201, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
Client[0] in group[0] is exiting...
Traceback (most recent call last):
  File "/develop/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 142, in <module>
    main(args)
  File "/develop/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 70, in main
    trainer.restore_model(model_path=config.restore_model_path)
  File "/develop/graphstorm/python/graphstorm/trainer/gsgnn_trainer.py", line 330, in restore_model
    self._optimizer.load_opt_state(model_path, self._model.device)
  File "/develop/graphstorm/python/graphstorm/model/gnn.py", line 100, in load_opt_state
    load_opt_state(path, self.dense_opts, self.lm_opts, self.sparse_opts)
  File "/develop/graphstorm/python/graphstorm/model/utils.py", line 609, in load_opt_state
    dense_opts[0].load_state_dict(checkpoint["lm"])
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/optimizer.py", line 201, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

```

To reproduce: 

```bash
# first fine-tune BERT model on arxiv for 1 epoch
python3  -m graphstorm.run.gs_node_classification \
            --workspace /tmp/ogbn-arxiv-nc \
            --num-trainers 8 \
            --num-servers 1 \
            --num-samplers 0 \
            --part-config /data/ogbn_arxiv_nc_train_val_1p_8t/ogbn-arxiv.json \
            --ip-config  /tmp/ogbn-arxiv-nc/ip_list.txt \
            --ssh-port 2222 \
            --cf /develop/graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml \
            --save-model-path /data/ogbn-arxiv-nc/models/bert_only/test \
            --save-perf-results-path /data/ogbn-arxiv-nc/models/bert_only/test \
            --lm-encoder-only \
            --batch-size 2048 \
            --num-epochs 1

# restore the model and optimizer from checkpoint
python3  -m graphstorm.run.gs_node_classification \
            --workspace /tmp/ogbn-arxiv-nc \
            --num-trainers 8 \
            --num-servers 1 \
            --num-samplers 0 \
            --part-config /data/ogbn_arxiv_nc_train_val_1p_8t/ogbn-arxiv.json \
            --ip-config  /tmp/ogbn-arxiv-nc/ip_list.txt \
            --ssh-port 2222 \
            --cf /develop/graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml \
            --save-model-path /data/ogbn-arxiv-nc/models/bert_only/test \
            --save-perf-results-path /data/ogbn-arxiv-nc/models/bert_only/test \
            --lm-encoder-only \
            --batch-size 2048 \
            --num-epochs 1 \
            --restore-model-path /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0 \
            --restore-optimizer-path /data/ogbn-arxiv-nc/models/bert_only/test/epoch-0

```

**Comment by wangz10** [comment]
@classicsong can you take a look at this?

**Comment by classicsong** [comment]
Are you using the newest code?
From your call stack I can see: 
```
File "/develop/graphstorm/python/graphstorm/model/utils.py", line 609, in load_opt_state
    dense_opts[0].load_state_dict(checkpoint["lm"])
```
But it should look like: 
https://github.com/awslabs/graphstorm/blob/8480c73febaa1bbcf9c7d711cd58ab8d376971b3/python/graphstorm/model/utils.py#L606-L608, where ```lm_opts[0]``` is going to load ```checkpoint["lm"]```

**Comment by wangz10** [comment]
Not the newest code. When I used the newest code and this bug is resolved. Thanks!
