### ISSUE TITLE
[Bug] GPU OOM when restoring optimizer state

### ISSUE THREAD

**Issue by wangz10** [awslabs/graphstorm#344]
When loading a model trained by graphstorm on the same hardware, I run into GPU OOM error:

```
Traceback (most recent call last):
  File "/develop/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 167, in <module>
    main(args)
  File "/develop/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 85, in main
    trainer.restore_model(model_path=config.restore_model_path,
  File "/develop/graphstorm/python/graphstorm/trainer/gsgnn_trainer.py", line 342, in restore_model
    self._optimizer.load_opt_state(model_path, self._model.device)
  File "/develop/graphstorm/python/graphstorm/model/gnn.py", line 107, in load_opt_state
    load_opt_state(path, self.dense_opts, self.lm_opts, self.sparse_opts)
  File "/develop/graphstorm/python/graphstorm/model/utils.py", line 596, in load_opt_state
    checkpoint = th.load(os.path.join(model_path, 'optimizers.bin'))
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1083, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 187, in _cuda_deserialize
    return obj.cuda(device)
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 80, in _cuda
    untyped_storage = torch.UntypedStorage(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 22.19 GiB total capacity; 1.90 GiB already allocated; 12.50 MiB free; 1.91 GiB reserved in total by PyTorch) If reserved memory is >> all
ocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by wangz10** [comment]
Adding `map_location='cpu'` fixed the bug.
