### ISSUE TITLE
[Bug] a bug in training on a homogeneous graph created from a built-in dataset.

### ISSUE THREAD

**Issue by zheng-da** [awslabs/graphstorm#360]
Our built-in graph partitioning pipeline has a bug on homogeneous graphs. Here is how we can reproduce the bug.

Construct a homogeneous graph.
```
python3 tools/partition_graph.py --dataset ogbn-products --filepath /tmp/ogbn-products/ --num-parts 1 --output /tmp/ogbn_products_1p
```
Use the following yaml file `products_nc.yaml`.
```
---
version: 1.0
gsf:
  basic:
    model_encoder_type: rgcn
    graph_name: ogbn-products
    backend: gloo
    verbose: false
  gnn:
    fanout: "15,10"
    num_layers: 2
    hidden_size: 128
    use_mini_batch_infer: false
  input:
    restore_model_path: null
  output:
    save_model_path: null
    save_embed_path: null
  hyperparam:
    dropout: 0.5
    lr: 0.001
    num_epochs: 10
    batch_size: 1024
    wd_l2norm: 0
  rgcn:
    num_bases: -1
    use_self_loop: true
    sparse_optimizer_lr: 1e-2
    use_node_embeddings: false
  node_classification:
    target_ntype: "node"
    label_field: "labels"
    multilabel: false
    num_classes: 40
```
use the following command to run the training job.
```
python3 -m graphstorm.run.gs_node_classification \
        --num-trainers 1 \
        --num-servers 1 \
        --num-samplers 1 \
        --part-config /tmp/ogbn_products_1p/ogbn-products.json \
        --ip-config ip_list.txt \
        --cf products_nc.yaml --node-feat-name feat
```

below is the error:
```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/graph-storm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 151, in <module>
    main(args)
  File "/home/ubuntu/workspace/graph-storm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 116, in main
    trainer.fit(train_loader=dataloader, val_loader=val_dataloader,
  File "/home/ubuntu/workspace/graph-storm/python/graphstorm/trainer/np_trainer.py", line 120, in fit
    for i, (input_nodes, seeds, blocks) in enumerate(train_loader):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dgl/distributed/dist_dataloader.py", line 115, in __next__
    self._request_next_batch()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dgl/distributed/dist_dataloader.py", line 147, in _request_next_batch
    result = self.collate_fn(next_data)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dgl/dataloading/dist_dataloader.py", line 202, in collate
    input_nodes, output_nodes, blocks = self.graph_sampler.sample_blocks(self.g, items)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dgl/dataloading/neighbor_sampler.py", line 141, in sample_blocks
    block.edata[EID] = eid
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dgl/view.py", line 227, in __setitem__
    self._graph._set_e_repr(self._etid, self._edges, {key: val})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dgl/heterograph.py", line 4133, in _set_e_repr
    raise DGLError('Expect number of features to match number of edges.'
dgl._ffi.base.DGLError: Expect number of features to match number of edges. Got 10158 and 0 instead.
Client[0] in group[0] is exiting...
```

**Comment by classicsong** [comment]
@jalencato Is this bug resolved?
