### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by Jonghyun-Yun** [awslabs/graphstorm#376]
While I was running examples for OGB MAG graph in `README.md`, I encounter out of memory error. The machine has 1 x NVIDIA Tesla K80 (12GB). Is this not enough? or should I suspect problems in other places? The below is backtrace:

```
python3 -m graphstorm.run.gs_node_classification         --workspace /tmp/ogbn-arxiv-nc         --num-trainers 1         --num-servers 1         --num-samplers 0         --part-config /tmp/ogbn_arxiv_nc_train_val_1p_4t/ogbn-arxiv.json         --ip-config  /tmp/ogbn-arxiv-nc/ip_list.txt         --ssh-port 2222         --cf /graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml         --save-perf-results-path /tmp/ogbn-arxiv-nc/models
cleanupu process runs
/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Namespace(ip_config='/tmp/ogbn-arxiv-nc/ip_list.txt', local_rank=-1, part_config='/tmp/ogbn_arxiv_nc_train_val_1p_4t/ogbn-arxiv.json', profile_path=None, save_perf_results_path='/tmp/ogbn-arxiv-nc/models', verbose=False, yaml_config_file='/graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml')
{'version': 1.0, 'gsf': {'basic': {'model_encoder_type': 'rgcn', 'graph_name': 'ogbn-arxiv', 'backend': 'gloo', 'ip_config': 'ip_list.txt', 'part_config': '/data/ogbn-arxiv-1p/ogbn-arxiv.json', 'verbose': False}, 'gnn': {'fanout': '15,10', 'num_layers': 2, 'hidden_size': 128, 'use_mini_batch_infer': False}, 'input': {'restore_model_path': None}, 'output': {'save_model_path': None, 'save_embed_path': None}, 'hyperparam': {'dropout': 0.5, 'lr': 0.001, 'num_epochs': 10, 'batch_size': 1024, 'wd_l2norm': 0}, 'rgcn': {'num_bases': -1, 'use_self_loop': True, 'sparse_optimizer_lr': '1e-2', 'use_node_embeddings': False}, 'node_classification': {'target_ntype': 'node', 'label_field': 'labels', 'multilabel': False, 'num_classes': 40}}}
Overriding Argument: profile_path
Overriding Argument: save_perf_results_path
Overriding Argument: ip_config
Overriding Argument: part_config
Overriding Argument: verbose
load ogbn-arxiv
start graph service on server 0 for part 0
[19:05:11] /opt/dgl/src/rpc/rpc.cc:141: Sender with NetType~socket is created.
[19:05:11] /opt/dgl/src/rpc/rpc.cc:161: Receiver with NetType~socket is created.
Server is waiting for connections on [127.0.0.1:30050]...
Namespace(ip_config='/tmp/ogbn-arxiv-nc/ip_list.txt', local_rank=0, part_config='/tmp/ogbn_arxiv_nc_train_val_1p_4t/ogbn-arxiv.json', profile_path=None, save_perf_results_path='/tmp/ogbn-arxiv-nc/models', verbose=False, yaml_config_file='/graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml')
{'version': 1.0, 'gsf': {'basic': {'model_encoder_type': 'rgcn', 'graph_name': 'ogbn-arxiv', 'backend': 'gloo', 'ip_config': 'ip_list.txt', 'part_config': '/data/ogbn-arxiv-1p/ogbn-arxiv.json', 'verbose': False}, 'gnn': {'fanout': '15,10', 'num_layers': 2, 'hidden_size': 128, 'use_mini_batch_infer': False}, 'input': {'restore_model_path': None}, 'output': {'save_model_path': None, 'save_embed_path': None}, 'hyperparam': {'dropout': 0.5, 'lr': 0.001, 'num_epochs': 10, 'batch_size': 1024, 'wd_l2norm': 0}, 'rgcn': {'num_bases': -1, 'use_self_loop': True, 'sparse_optimizer_lr': '1e-2', 'use_node_embeddings': False}, 'node_classification': {'target_ntype': 'node', 'label_field': 'labels', 'multilabel': False, 'num_classes': 40}}}
Overriding Argument: profile_path
Overriding Argument: save_perf_results_path
Overriding Argument: ip_config
Overriding Argument: part_config
Overriding Argument: verbose
[19:05:12] /opt/dgl/src/rpc/rpc.cc:141: Sender with NetType~socket is created.
[19:05:12] /opt/dgl/src/rpc/rpc.cc:161: Receiver with NetType~socket is created.
Client [710] waits on 127.0.0.1:52427
Machine (0) group (0) client (0) connect to server successfuly!
Traceback (most recent call last):
  File "/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 151, in <module>
    main(args)
  File "/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 64, in main
    train_data = GSgnnNodeTrainData(config.graph_name,
  File "/graphstorm/python/graphstorm/dataloading/dataset.py", line 596, in __init__
    super(GSgnnNodeTrainData, self).__init__(graph_name, part_config,
  File "/graphstorm/python/graphstorm/dataloading/dataset.py", line 504, in __init__
    super(GSgnnNodeData, self).__init__(graph_name, part_config,
  File "/graphstorm/python/graphstorm/dataloading/dataset.py", line 131, in __init__
    self.prepare_data(self._g)
  File "/graphstorm/python/graphstorm/dataloading/dataset.py", line 631, in prepare_data
    if dist_sum(len(val_idx)) > 0:
  File "/graphstorm/python/graphstorm/dataloading/utils.py", line 66, in dist_sum
Client[0] in group[0] is exiting...
    size = th.tensor([size], device=th.device(dev_id))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Server (0) shutdown.
Server is exiting...
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 710) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-09_19:05:20
  host      : localhost
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 710)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Called process error Command 'ssh -o StrictHostKeyChecking=no -p 2222 127.0.0.1 'cd /tmp/ogbn-arxiv-nc; (export DGL_DIST_MODE=distributed DGL_ROLE=client DGL_NUM_SAMPLER=0 DGL_NUM_CLIENT=1 DGL_CONF_PATH=/tmp/ogbn_arxiv_nc_train_val_1p_4t/ogbn-arxiv.json DGL_IP_CONFIG=/tmp/ogbn-arxiv-nc/ip_list.txt DGL_NUM_SERVER=1 DGL_GRAPH_FORMAT=csc OMP_NUM_THREADS=3 DGL_GROUP_ID=0 PYTHONPATH=/graphstorm/python/: ; /usr/bin/python3 -u -m torch.distributed.launch --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=1234 /graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py --cf /graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml --save-perf-results-path /tmp/ogbn-arxiv-nc/models --ip-config /tmp/ogbn-arxiv-nc/ip_list.txt --part-config /tmp/ogbn_arxiv_nc_train_val_1p_4t/ogbn-arxiv.json --verbose False)'' returned non-zero exit status 1.
Task failed
```

**Comment by isratnisa** [comment]
Hi! Can you please try with smaller `fanout` and `hidden_size`? For example we can change the config file (`/graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml`) according to the following:
```
    fanout: "2"
    num_layers: 1
    hidden_size: 4
```

**Comment by isratnisa** [comment]
Also, to be sure, is the dataset partitioned into only 1 part?

**Comment by Jonghyun-Yun** [comment]
I cannot run the smaller problem in GPU. It works with CPU though. Let me talk to people in my group, and come back to this.
