### ISSUE TITLE
Cannot do inference on Torch 2.1.0+CUDA11.8 with multi samplers

### ISSUE THREAD

**Issue by jalencato** [awslabs/graphstorm#531]
## 🐛 Bug 

Training script as tutorial suggested can not work with multi samplers on Torch 2.1.0+CUDA11.8, simply training is fine but we can not do inference with multi samplers.
 
## Note: 

Things work good for num_samplers = 0
I am running with 
```
ulimit -n
1048576
```
So I cannot increase the ulimit any more as I reach the maximum which is suggested by the solution here https://github.com/pytorch/pytorch/issues/973.

## Command: 
When I run training command here:
```
python3 -m graphstorm.run.gs_node_classification \
        --workspace /tmp/ogbn-arxiv-nc \
        --num-trainers 1 \
        --num-servers 1 \
        --num-samplers 4 \
        --part-config /tmp/ogbn_arxiv_nc_train_val_1p_4t/ogbn-arxiv.json \
        --ip-config  /tmp/ogbn-arxiv-nc/ip_list.txt \
        --ssh-port 2222 \
        --cf /graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml \
        --save-perf-results-path /tmp/ogbn-arxiv-nc/models
```

I meet the problem:
```
Traceback (most recent call last):
  File "/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 171, in <module>
    main(args)
  File "/graphstorm/python/graphstorm/run/gsgnn_np/gsgnn_np.py", line 154, in main
    embeddings = do_full_graph_inference(model, train_data, fanout=config.eval_fanout,
  File "/graphstorm/python/graphstorm/model/gnn.py", line 993, in do_full_graph_inference
    embeddings = model.gnn_encoder.dist_inference(data.g, get_input_embeds,
  File "/graphstorm/python/graphstorm/model/gnn_encoder_base.py", line 102, in dist_inference
    return dist_inference(g, self, get_input_embeds, batch_size, fanout,
  File "/graphstorm/python/graphstorm/model/gnn_encoder_base.py", line 363, in dist_inference
    next_layer_input = dist_inference_one_layer(str(i), g, dataloader,
  File "/graphstorm/python/graphstorm/model/gnn_encoder_base.py", line 235, in dist_inference_one_layer
    len_dataloader = max_num_batch = len(list(dataloader))
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/dist_dataloader.py", line 117, in __next__
    result = self._get_data_from_result_queue()
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/dist_dataloader.py", line 129, in _get_data_from_result_queue
    ret = self.pool.get_result(self.name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/dist_context.py", line 180, in get_result
    dl_name, data = self.result_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/reductions.py", line 355, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 164, in recvfds
    raise RuntimeError('received %d items of ancdata' %
RuntimeError: received 0 items of ancdata
```

I can do training only with no-validation flag:
```
python3 -m graphstorm.run.gs_node_classification \
        --workspace /tmp/ogbn-arxiv-nc \
        --num-trainers 1 \
        --num-servers 1 \
        --num-samplers 1 \
        --part-config /tmp/ogbn_arxiv_nc_train_val_1p_4t/ogbn-arxiv.json \
        --ip-config  /tmp/ogbn-arxiv-nc/ip_list.txt \
        --ssh-port 2222 \
        --cf /graphstorm/training_scripts/gsgnn_np/arxiv_nc.yaml \
        --save-perf-results-path /tmp/ogbn-arxiv-nc/models \
        --no-validation true
```

**Comment by zheng-da** [comment]
after this PR (https://github.com/awslabs/graphstorm/pull/580) is merged, is this bug fixed?

**Comment by jalencato** [comment]
The bug here is fixed. Now we can use multiple samplers by upgrading the torch version.
