### ISSUE TITLE
[Bug] Mismatched matrix shapes in input_projs from `GSNodeEncoderInputLayer.forward`

### ISSUE THREAD

**Issue by wangz10** [awslabs/graphstorm#550]
I run into this error when using the latest version of graphstorm 9f5218320fc49a2d30a6dab6475ed69810e5fbd7, on a link prediction task with RGCN with frozen LMs: 

```
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
INFO:root:part 0, train: 851263, val: 106407, test: 106412
Some weights of RobertaModel were not initialized from the model checkpoint at DeepChem/ChemBERTa-77M-MLM and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
INFO:root:yaml_paths: frozen_lm_rgcn_lp.yaml
INFO:root:_node_lm_configs: [{'lm_type': 'bert', 'model_name': 'Rostlab/prot_bert', 'gradient_checkpoint': True, 'node_types': ['protein']}, {'lm_type': 'roberta', 'model_name': 'DeepChem/ChemBERTa-77M-MLM', 'gradient_checkpoint': True, 'node_types': ['drug']}, {'lm_type': 'bert', 'model_name': 'microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext', 'gradient_checkpoint': True, 'node_types': ['disease', 'function', 'sideeffect']}]
INFO:root:_backend: nccl
INFO:root:_verbose: False
INFO:root:_save_perf_results_path: /industry-gml-benchmarks/ogbl-biokg/dataset/ogbl_biokg/biokg_graph_tasks/1_ppi/frozen_lm_rgcn_lp_model
INFO:root:_model_encoder_type: rgcn
INFO:root:_use_self_loop: False
INFO:root:_lm_train_nodes: 0
INFO:root:_lm_infer_batch_size: 32
INFO:root:_freeze_lm_encoder_epochs: 0
INFO:root:_hidden_size: 128
INFO:root:_use_mini_batch_infer: True
INFO:root:_num_layers: 2
INFO:root:_dropout: 0.0
INFO:root:_lr: 0.001
INFO:root:_num_epochs: 3
INFO:root:_batch_size: 128
INFO:root:_eval_batch_size: 1024
INFO:root:_wd_l2norm: 0
INFO:root:_fanout: 5,5
INFO:root:_eval_fanout: 20,20
INFO:root:_no_validation: False
INFO:root:_eval_frequency: 500
INFO:root:_restore_model_path: None
INFO:root:_save_model_path: /industry-gml-benchmarks/ogbl-biokg/dataset/ogbl_biokg/biokg_graph_tasks/1_ppi/frozen_lm_rgcn_lp_model
INFO:root:_save_embed_path: None
INFO:root:_num_negative_edges: 4
INFO:root:_num_negative_edges_eval: 100
INFO:root:_train_negative_sampler: joint
INFO:root:_eval_etype: ['protein,protein-protein_activation,protein', 'protein,protein-protein_binding,protein', 'protein,protein-protein_catalysis,protein', 'protein,protein-protein_expression,protein', 'protein,protein-protein_inhibition,protein', 'protein,protein-protein_ptmod,protein', 'protein,protein-protein_reaction,protein']
INFO:root:_train_etype: ['protein,protein-protein_activation,protein', 'protein,protein-protein_binding,protein', 'protein,protein-protein_catalysis,protein', 'protein,protein-protein_expression,protein', 'protein,protein-protein_inhibition,protein', 'protein,protein-protein_ptmod,protein', 'protein,protein-protein_reaction,protein']
INFO:root:_exclude_training_targets: False
INFO:root:_reverse_edge_types_map: []
INFO:root:_task_type: link_prediction
INFO:root:_logging_level: info
INFO:root:_profile_path: None
INFO:root:_construct_feat_ntype: None
INFO:root:_ip_config: /industry-gml-benchmarks/ogbl-biokg/ip_list.txt
INFO:root:_part_config: /industry-gml-benchmarks/ogbl-biokg/dataset/ogbl_biokg/biokg_graph_tasks/1_ppi/biokg.json
INFO:root:local_rank: 0
INFO:root:Computing bert embedding on node protein takes 258.952 seconds
INFO:root:Computing bert embedding on node drug takes 4.230 seconds
INFO:root:Computing bert embedding on node disease takes 39.415 seconds
INFO:root:Computing bert embedding on node function takes 166.670 seconds
INFO:root:Computing bert embedding on node sideeffect takes 36.788 seconds
/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py:1772: UserWarning: You passed find_unused_parameters=true to DistributedDataParallel, `_set_static_graph` will detect unused parameters automatically, so you do not need to set find_unused_parameters=true, just be sure these unused parameters will not change during training loop while calling `_set_static_graph`.
  warnings.warn(
Traceback (most recent call last):
  File "/develop/graphstorm/python/graphstorm/run/gsgnn_lp/gsgnn_lp.py", line 217, in <module>
    main(args)
  File "/develop/graphstorm/python/graphstorm/run/gsgnn_lp/gsgnn_lp.py", line 180, in main
    trainer.fit(train_loader=dataloader, val_loader=val_dataloader,
  File "/develop/graphstorm/python/graphstorm/trainer/lp_trainer.py", line 191, in fit
    loss = model(blocks, pos_graph, neg_graph,
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/develop/graphstorm/python/graphstorm/model/lp_gnn.py", line 95, in forward
    encode_embs = self.compute_embed_step(blocks, node_feats, input_nodes)
  File "/develop/graphstorm/python/graphstorm/model/gnn.py", line 782, in compute_embed_step
    embs = self.node_input_encoder(input_feats, input_nodes)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/develop/graphstorm/python/graphstorm/model/lm_embed.py", line 704, in forward
    return super(GSLMNodeEncoderInputLayer, self).forward(input_feats, input_nodes)
  File "/develop/graphstorm/python/graphstorm/model/embed.py", line 295, in forward
    emb = input_feats[ntype].float() @ self.input_projs[ntype]
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2227x768 and 1024x128)
```

However, the task can be completed without this encountering error when using v0.1.2 version.

**Comment by classicsong** [comment]
Can you try v0.2?

**Comment by wangz10** [comment]
Got the same error.

**Comment by wangz10** [comment]
I think I found the root cause. The [`adjust_feat_size`](https://github.com/awslabs/graphstorm/blob/v0.1.2/python/graphstorm/model/lm_embed.py#L329C1-L343C1) used to be determined by individual LMs in v0.1.2. 

In v0.2, the `feat_size` property only use the first lm model's feat_size as the collection of LM's feat_size. https://github.com/awslabs/graphstorm/blob/9f5218320fc49a2d30a6dab6475ed69810e5fbd7/python/graphstorm/model/lm_embed.py#L194C1-L201C18

This exclude the cases where multiple LMs with different feat_size's.

**Comment by classicsong** [comment]
Can we close this issue?
