### ISSUE TITLE
Find a Bug when testing on torch 2.1.0+cuda 121 and dgl 2.0.0+cuda 121

### ISSUE THREAD

**Issue by jalencato** [awslabs/graphstorm#753]
```

  | 2024-02-26T22:17:19.194Z | Traceback (most recent call last):
  | 2024-02-26T22:17:19.194Z | File "/usr/local/lib/python3.8/dist-packages/graphstorm/run/gsgnn_np/gsgnn_np.py", line 189, in <module>
  | 2024-02-26T22:17:19.194Z | main(gs_args)
  | 2024-02-26T22:17:19.194Z | File "/usr/local/lib/python3.8/dist-packages/graphstorm/run/gsgnn_np/gsgnn_np.py", line 142, in main
  | 2024-02-26T22:17:19.194Z | trainer.fit(train_loader=dataloader, val_loader=val_dataloader,
  | 2024-02-26T22:17:19.194Z | File "/usr/local/lib/python3.8/dist-packages/graphstorm/trainer/np_trainer.py", line 189, in fit
  | 2024-02-26T22:17:19.194Z | self.optimizer.step()
  | 2024-02-26T22:17:19.194Z | File "/usr/local/lib/python3.8/dist-packages/graphstorm/model/gnn.py", line 119, in step
  | 2024-02-26T22:17:19.194Z | optimizer.step()
  | 2024-02-26T22:17:19.194Z | File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/optim/pytorch/sparse_optim.py", line 355, in step
  | 2024-02-26T22:17:19.194Z | alltoall(
  | 2024-02-26T22:17:19.194Z | File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/optim/pytorch/utils.py", line 88, in alltoall
  | 2024-02-26T22:17:19.194Z | alltoall_cpu(
  | 2024-02-26T22:17:19.194Z | File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/optim/pytorch/utils.py", line 26, in alltoall_cpu
  | 2024-02-26T22:17:19.194Z | dist.scatter(
  | 2024-02-26T22:17:19.194Z | File "/usr/local/lib/python3.8/dist-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
  | 2024-02-26T22:17:19.194Z | return func(*args, **kwargs)
  | 2024-02-26T22:17:19.194Z | File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 3174, in scatter
  | 2024-02-26T22:17:19.195Z | work = default_pg.scatter(output_tensors, input_tensors, opts)
  | 2024-02-26T22:17:19.195ZRuntimeError: ProcessGroupGloo::scatter: invalid tensor type at index 0 (expected TensorOptions(dtype=long int, device=cuda:0, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)), got TensorOptions(dtype=long int, device=cpu, layout=Strided, requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt)))
```
You can reproduce the problem by applying RGCN/RGAT on ogbn-arxiv training on node classification task. 

The error will occur when we are trying to use conv layer from dglnn inside the RGCN/RGAT/SAGE/GAT. 

It works with dgl v1.1.3

**Comment by classicsong** [comment]
Fixed?
