### ISSUE TITLE
The runtime error running gconstruct in the graphstorm

### ISSUE THREAD

**Issue by znyzhouwl** [awslabs/graphstorm#942]
The following error appears

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.9/site-packages/graphstorm/gconstruct/construct_graph.py", line 936, in <module>
    process_graph(argparser.parse_args())
  File "/opt/conda/lib/python3.9/site-packages/graphstorm/gconstruct/construct_graph.py", line 834, in process_graph
    g = dgl.heterograph(edges, num_nodes_dict=num_nodes)
  File "/opt/conda/lib/python3.9/site-packages/dgl/convert.py", line 331, in heterograph
    (sparse_fmt, arrays), urange, vrange = utils.graphdata2tensors(
  File "/opt/conda/lib/python3.9/site-packages/dgl/utils/data.py", line 186, in graphdata2tensors
    data.format, tuple(F.tensor(a) for a in data.arrays)
  File "/opt/conda/lib/python3.9/site-packages/dgl/utils/data.py", line 186, in <genexpr>
    data.format, tuple(F.tensor(a) for a in data.arrays)
  File "/opt/conda/lib/python3.9/site-packages/dgl/backend/pytorch/tensor.py", line 53, in tensor
    return th.as_tensor(data, dtype=dtype)
RuntimeError: Could not infer dtype of numpy.int64

A similar issue: https://github.com/pytorch/pytorch/issues/102026

when I run gconstruct to construct the graph.

**Versions**
graphstorm        0.3
torch          2.1.0+cu118
dgl           1.1.3+cu118
Python  3.9.4

**Comment by qwangry** [comment]
Have you solved this problem?

**Comment by classicsong** [comment]
The issue is related to https://github.com/pytorch/pytorch/issues/102026.
You can use higher version or torch and dgl to solve the problem.

**Comment by qwangry** [comment]
> The issue is related to [pytorch/pytorch#102026](https://github.com/pytorch/pytorch/issues/102026). You can use higher version of torch and dgl to solve the problem.

I have tried many newer versions, but since I am on Windows, PyTorch and DGL are not compatible, resulting in the error: "FileNotFoundError: Cannot find DGL C++ graphbolt library at D:\Python39\lib\site-packages\dgl\graphbolt\graphbolt_pytorch_2.4.1.dll". When I revert to compatible versions, it shows: "RuntimeError: Could not infer dtype of numpy.int64".

**Comment by classicsong** [comment]
You need to create an issue in DGL's repo.
For GraphStorm, we only tested it on Linux environments.

**Comment by qwangry** [comment]
> You need to create an issue in DGL's repo. For GraphStorm, we only tested it on Linux environments.

Okay, thank you!
